### ISSUE TITLE
ncPRO app requires "Read Count" column

### ISSUE THREAD

**Issue by plger** [uzh/ezRun#111]
When the "Read Count" column is absent from the dataset definition, the app stops with 
```Error in `$<-.data.frame`(`*tmp*`, removed, value = integer(0))  ```

I suspect this is due too this part of the app:
https://github.com/uzh/ezRun/blob/6992d62149135128ff2d9e2e22048f1ffc63598b/R/app-ncpro.R#L88-L100

(More specifically line 93)

I haven't tried, but putting it under the line 88 conditional could probably solve the issue; alternatively, making `Read Count` a necessary column (e.g. in the sushi app) obviously does solve the problem.

**Comment by hrehrauer** [comment]
I fixed this with
 if (!is.null(dataset$"Read Count") && is.numeric(dataset$"Read Count") && all(dataset$"Read Count" > 0)){
    readCounts$untrimmed = dataset[samples, "Read Count"]    
  } else {
    readCounts$untrimmed = countReadsInFastq(fqFiles[samples])
  }
