### ISSUE TITLE
10x like Median Genes per Cell saturant plot in SCCountQC

### ISSUE THREAD

**Issue by ge11232002** [uzh/ezRun#118]
https://fgcz-gstore.uzh.ch/projects/p2220/CellRangerCount_35138_NOV86_o5444_2019-04-26--11-17-58/Differentiated_lung_cells/outs/web_summary.html

**Comment by ge11232002** [comment]
1st thing to try: subsample the gene-cell count matrix.

**Comment by hrehrauer** [comment]
I am wondering how they define the saturation curve. Especially the saturation value. I guess they fit an asymptotic curve first.

**Comment by ge11232002** [comment]
CellRanger calculates the saturation curvie in this way: https://kb.10xgenomics.com/hc/en-us/articles/115005062366-What-is-sequencing-saturation-, https://kb.10xgenomics.com/hc/en-us/articles/115003646912-How-is-sequencing-saturation-calculated-

It's not possible to do the same for Smart-seq2. I implemented the "Median Genes per Cell" curve by downsampling the sequencing depth.

Implemented in 9e0b5878dfcbf598110943a7ce25c76b2e612bf0
