### ISSUE TITLE
plot dendrogram with colour in countQC

### ISSUE THREAD

**Issue by ge11232002** [uzh/ezRun#27]
Better visualisation of groups in the dendrogram.

**Comment by hrehrauer** [comment]
good idea!
On that topic, we use graded colors for the different replicates. I think now, in the case of many replicates one would rather prefer to have all colors the same. One could simply update the getSampleColors function.

**Comment by ge11232002** [comment]
Now dendrogram has the color band of "Factor" columns
![sample clustering-1](https://user-images.githubusercontent.com/976443/31768117-2e01dd4a-b4ce-11e7-84c3-abb6512b0871.png)

**Comment by ge11232002** [comment]
close via 29ce0b7a127085f0002336ba896140affa1021f3
